version: '3.7'

services:

    project_name:
        image: ${PROJECT_NAME_IMAGE_NAME:-project_name}
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        depends_on:
            - mongo
        stdin_open: true
        tty: true
        container_name: project_name
        environment:
            - DB_USER=mongoadmin
            - DB_PASSWORD=secret
            - DB_URI=mongodb://mongo:27017/project_name?authSource=admin
            - SUBSCRIPTION_NAME=subscription_name
            - PUBSUB_EMULATOR_HOST=pubsub_emulator:8432
            - PUBSUB_PROJECT_ID=fake_project

        volumes:
            - ./:/app
            - project_name_dist:/app/dist
            - project_name_node_modules:/app/node_modules
        ports:
            - 8080:8080
            - 9229:9229

    mongo:
        image: mongo:4.4-bionic
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - 27017:27017

    mongo_express:
        image: mongo-express
        container_name: mongo_express
        logging:
            driver: none
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
        ports:
            - 8081:8081

    pubsub_emulator:
        image: storytel/gcp-pubsub-emulator
        container_name: pubsub_emulator
        ports:
            - 8432:8432
        command: --host=0.0.0.0 --port=8432



volumes:
    project_name_node_modules:
    project_name_dist:
networks:
    default:
        name: project_name-environment-network
